services:
  api:
    build: ..
    environment:
      # Note: in the hostname, we must use the name of the database container (so its "db" instead of typical "locahost")
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_LOGGING_LEVEL_ROOT: INFO
      SPRING_SERVER_PORT: 8080
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  my-db: